name: fixer_app
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutterflow_ui_pro:
    git:
      url: https://github.com/joeshwoa/flutterflow_ui_pro
      ref: main   # Optional: specify the branch, commit, or tag if needed
  flutter_spinkit: ^5.2.1
  adaptive_theme: ^3.6.0
  shared_preferences: ^2.3.1
  dio: ^5.5.0+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.2.6
  http: ^1.2.2
  pdf: ^3.11.1
  path_provider: ^2.1.4
  printing: ^5.13.1
  url_launcher: ^6.3.0


#dependency_overrides:

  #pdf_widget_wrapper: ^1.0.4


  auto_size_text: any
  google_fonts: any
  flutter_animate: any
  percent_indicator: any
  smooth_page_indicator: any
dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: ^4.0.0
  image: ^4.2.0
  lints: ^4.0.0
  icons_launcher: ^2.1.7

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/Hacen_Tunisia/

icons_launcher:
  image_path: "assets/images/android_app_icon.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#FFEEDD"
      adaptive_foreground_image: "assets/images/android_app_icon.png"
    ios:
      enable: true
      image_path: "assets/images/apple_app_Icon.png"
