const Map<String, String> ar = {

  //User
  'Your Car':'سيارتك',
  'Last Visit':'الزيارة السابقة',
  'Status':'الحالة',
  'The Expected completion date':'التاريخ المتوقع للانتهاء',
  'Regular Services':'صيانات دورية',
  'Non-Regular Services':'صيانات غير دورية',
  'Next Service Date':'تاريخ الصيانة القادمة',
  'Login Successfully':'تم تسجيل الدخول',
  'Failed to Login':'فشل تسجيل الدخول',
  'Welcome!':'مرحبا بك!',
  'To the future of car service':'مستقبل الصيانة في مصر',
  'Code':'كود',
  'Please enter your code':'من فضلك ادخل الكود',
  'Password':'الرقم السري',
  'Please enter your password':'من فضلك ادخل الرقم السري',
  'Don\'t have an account?':'لا تمتلك حساب؟',
  'Visit our center to create \nan account':'زور موقعنا لانشاء \nحساب',
  'Login':'دخول',
  'Login with saved account?':'تسجيل دخول بحسابات مسجلة مسبقا؟',
  'Forgot your password?':'نسيت رقمك السري؟',
  'Visit our Social Pages':'زور صفحاتنا الاجتماعية',
  'E':'ع',
  'Home':'الرئيسية',
  'Services':'صيانات',
  'Person':'صفحة شخصية',
  'Forgot Password':'نسيت الرقم السري',
  'Your Code...':'كودك...',
  'Enter your code here...':'اكتب الكود الخاص بك هنا...',
  'Car Plate':'لوحة السيارة',
  'Characters':'حروف',
  'Enter characters here...':'اكتب الحروف هنا...',
  'Numbers':'ارقام',
  'Enter numbers here...':'اكتب الارقام هنا...',
  'We will send you your password using email.':'سوف نرسل لك عن طريق الايميل رقمك السري',
  'Send You Your Password':'ارسال رقمك السري لك',
  'Enter car code':'اكتب كود السيارة',
  'Enter car plate characters':'اكتب حروف لوحة السيارة',
  'Enter car plate number':'اكتب ارقام لوحة السيارة',
  'Your saved accounts':'حساباتك المسجلة من قبل',
  'Login with new account?':'تسجيل بحساب جديد؟',
  'My Car':'سيارتي',
  'Car Type':'نوع السيارة',
  'Color':'اللون',
  'Model':'موديل',
  'Distance':'عداد المسافة',
  'Chassis Number':'رقم الشاسيه',
  'Motor Number':'رقم الماتور',
  'My Profile':'ملفي الشخصي',
  'Full Name':'الاسم كامل',
  'Your full name...':'اسمك الكامل...',
  'Email Address':'عنوان البريد الالكتروني',
  'Your email...':'بريدك الالكتروني...',
  'Phone Number':'رقم الهاتف',
  'Your phone...':'رقم هاتفك...',
  'Fix Your Cars':'اصلح سياراتك',
  'Keep all your cars on way with fixer, you always have best performance.':'اجعل جميع سياراتك علي الطريق مع Fixer دائما تحصل علي اعلي اداء.',
  'Keep Tracking':'استمر في تتبع',
  'Always track your cars\'s services, performance and bills.':'تتبع دائما صيانات، و اداء، و فواتير سياراتك.',
  'Service Reminder':'مذكر بالصيانات',
  'Always keep your cars in best performance by making them regular services.':'دائما اجعل سياراتك باحسن اداء عن طريق اجراء الصيانات الدورية',
  'Continue':'استمر',
  'Switch to Dark Mode':'حول الي الوضع المظلم',
  'Switch to Light Mode':'حول الي الوضع المضئ',
  'Log Out':'تسجيل خروج',
  'Service Type':'نوع الصيانة',
  'Expected Completion Date':'تاريخ الانتهاء المتوقع',
  'Bill':'الفاتورة',
  'EGP':'ج.م',
  'Additions':'اضافات',
  'My Service':'صياناتي',
  'No Services Found':'لا يوجد صيانات',
  'Labour':'مصنعيات',
  'Spare Parts':'قطع غيار',
  'Price After Discount':'السعر بعد الخصم',
  'Completion Ratio':'نسبة الخصم',
  'Service':'مصنعية',
  'Completed On':'تمت',
  'Completed':'تمت',
  'Repairing':'جاري العمل علبها',
  'In Progress':'جاري العمل',
  'New Update': 'تحديث جديد',
  'New Version Available Now': 'تحديث جديد متوفر',
  'Download New Version': 'تحميل النسخة الجديدة',
  'Good': 'جيد',
  'Repair': 'في صيانة',
  'Need to check': 'تحتاج الي فحص',
  'Km': 'كم',
  'Regular':'دورية',
  'Non-Regular':'غير دورية',
  'Next Service Distance': 'مسافة الصيانة القادمة',
  'Powered by': 'يعمل بواسطة',
};